[workspace]
resolver = "2"

members = [
  "ctf-bump",
  "ctf-bump/meta",
  "ctf-coinflip",
  "ctf-coinflip/meta",
  "ctf-try-the-coinflip",
  "ctf-try-the-coinflip/meta",
  "ctf-gaspass",
  "ctf-gaspass/meta",
  "bump-common",
  "interact",
]
